GET http://localhost:5128/animes

###
GET http://localhost:5128/animes/4

###
POST http://localhost:5128/animes
Content-Type: application/json

{
    "name": "Sousou no Frieren",
    "genreId": 1,
    "numberEpisodes": 13,
    "releaseDate": "2023-09-29"
}

###
PATCH http://localhost:5128/animes/4
Content-Type: application/json

{
    "name": "Oshi no Ko II",
    "genre": "Drama",
    "numberEpisodes": 11,
    "releaseDate": "2023-04-12"
}

###
DELETE http://localhost:5128/animes/4